
CREATE DATABASE IF NOT EXISTS ninos;
USE ninos;

CREATE TABLE IF NOT EXISTS NINOS (
    num INT AUTO_INCREMENT PRIMARY KEY,
    Folio VARCHAR(100),
    ID VARCHAR(100),
    NOMBRE VARCHAR(100),
    APELLIDOS VARCHAR(100),
    GENERO VARCHAR(100),
    F_NACIMIENTO VARCHAR(100),
    DOMICILIO VARCHAR(100),
    COLONIA VARCHAR(100),
    MUNICIPIO VARCHAR(100),
    GRADO_ESC VARCHAR(100),
    ESCUELA VARCHAR(100),
    CURP VARCHAR(100),
    EDAD INT
);

